services:
  auth-db:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - auth-vol:/var/lib/postgresql/data

  auth-api:
    build: .
    depends_on:
      - auth-db
    ports:
      - "4002:4002"
    env_file: .env

    # Possibly use
    # stdin_open: true
    # tty: true

volumes:
  auth-vol:
