services:
  frontend-dev:
    image: nginx:1.27.0-alpine
    build: .
    volumes:
      - './:/app/'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    profiles:
      - dev

  frontend-prod:
    image: nginx:1.27.0-alpine
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    profiles:
      - prod
