services:
  auth_api:
    build:
      context: backend/auth
      no_cache: true
    depends_on:
      auth_db:
        condition: service_healthy
    ports:
      - "4002:4002"
    networks:
      - todo_microservices
    env_file: backend/auth/.env
    restart: on-failure
    links:
      - auth_db

  todo_api:
    build:
      context: backend/todos
      no_cache: true
    depends_on:
      todo_db:
        condition: service_healthy
    ports:
      - "4001:4001"
    networks:
      - todo_microservices
    env_file: backend/todos/.env
    restart: on-failure
    links:
      - todo_db

  auth_db:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - todo_microservices
    volumes:
      - auth-vol:/var/lib/postgresql/data

  todo_db:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - todo_microservices
    volumes:
      - todo-vol:/var/lib/postgresql/data

volumes:
  todo-vol:
  auth-vol:

networks:
  todo_microservices:
