services:
  auth_api:
    build:
      context: backend/auth
    depends_on:
      auth_db:
        condition: service_healthy
    ports:
      - "4002:4002"
    networks:
      - todo_microservices
    env_file: backend/auth/.env
    restart: on-failure
    links:
      - auth_db

  todo_api:
    build:
      context: backend/todos
    depends_on:
      todo_db:
        condition: service_healthy
    ports:
      - "4001:4001"
    networks:
      - todo_microservices
    env_file: backend/todos/.env
    restart: on-failure
    links:
      - todo_db

  auth_db:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - todo_microservices
    volumes:
      - auth-vol:/var/lib/postgresql/data

  todo_db:
    image: postgres:16
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - todo_microservices
    volumes:
      - todo-vol:/var/lib/postgresql/data

  gateway:
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
    networks:
      - todo_microservices
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo_api
      - auth_api

  frontend-dev:
    build:
      context: ./frontend
    volumes:
      - "./frontend:/app/"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    restart: on-failure
    networks:
      - todo_microservices
    profiles:
      - dev

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    networks:
      - todo_microservices
    profiles:
      - prod

volumes:
  todo-vol:
  auth-vol:

networks:
  todo_microservices:
